[package]
name = "mujo-jojo"
version = "0.1.0"
edition = "2024"

[dependencies]
mujoco-sys = { path = "../../../mujoco-sys" }
glfw-sys = "6.0.0"
glow = "0.16.0"
nalgebra = "0.34.1"
ndarray = "0.17.1"
ndarray-linalg = "0.18.0"
